export const TYPE_ON_WALL_TEXTAREA = 'TYPE_ON_WALL_TEXTAREA';
export const ADD_POST = 'ADD_POST';
export const EDIT_POST = 'EDIT_POST';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SET_CONVERSATION_ID = 'SET_CONVERSATION_ID';
export const TYPE_ON_PRIMARY_MESSAGE_TEXTAREA = 'TYPE_ON_PRIMARY_MESSAGE_TEXTAREA';
export const SET_TO_NULL_UNREAD_COUNTER = 'SET_TO_NULL_UNREAD_COUNTER';

export const SET_CONTACTS = 'SET_CONTACTS';
export const SET_USER_MESSAGES = 'SET_USER_MESSAGES';


export const USER_STATUS_TEXT_HANDLER = 'USER_STATUS_TEXT_HANDLER';
export const USER_NAME_SETTINGS_HANDLER = 'USER_NAME_SETTINGS_HANDLER';
export const USER_EMAIL_SETTINGS_HANDLER = 'USER_EMAIL_SETTINGS_HANDLER';
export const USER_PHOTO_SETTINGS_HANDLER = 'USER_PHOTO_SETTINGS_HANDLER';
export const USER_PROFILE_PIC_HANDLER = 'USER_EMAIL_SETTINGS_HANDLER';
export const USER_GENDER_SETTINGS_HANDLER = 'USER_GENDER_SETTINGS_HANDLER';
export const USER_AGE_SETTINGS_HANDLER = 'USER_AGE_SETTINGS_HANDLER';
export const USER_CITY_SETTINGS_HANDLER = 'USER_CITY_SETTINGS_HANDLER';
export const SET_USER_INFO_AFTER_LOGIN = 'SET_USER_INFO_AFTER_LOGIN';
export const SET_AUTHORIZED = 'SET_AUTHORIZED';
export const SET_LOGIN = 'SET_LOGIN';
export const SET_PASS = 'SET_PASS';